import keyboard
import time
time.sleep(7)

for x in range(18):
    keyboard.press_and_release('cmd+c')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)

# kopieer naam
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('space')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)

    # kopieer naam
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.3)

    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('tab')
    time.sleep(0.2)      
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)

    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)  

# omschrijving 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('cmd+c')
    time.sleep(0.1)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.3)
    keyboard.press_and_release('cmd+v')

# adres
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1)

    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)

    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.1)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)

# adres 3
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.3)
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.3)

    keyboard.press_and_release('tab')
    time.sleep(0.3)
    keyboard.press_and_release('cmd+c')
    time.sleep(0.3)
    keyboard.press_and_release('cmd+tab')
    time.sleep(0.3)
    keyboard.press_and_release('tab')
    time.sleep(0.2)
    keyboard.press_and_release('cmd+v')

    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1)  
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.2) 
    keyboard.press_and_release('tab')
    time.sleep(0.2)   
    keyboard.press_and_release('enter')
    time.sleep(0.3)
    keyboard.press_and_release('enter')
    time.sleep(2.5)
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.1) 
    keyboard.press_and_release('tab')
    time.sleep(0.5) 
    keyboard.press_and_release('enter')
    time.sleep(2.5)

    keyboard.press_and_release('cmd+tab')
    time.sleep(0.1)   
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('left')
    time.sleep(0.1) 
    keyboard.press_and_release('enter')
    time.sleep(1) 


print("finish")